### ISSUE TITLE
Duplicate files?

### ISSUE THREAD

**Issue by rxng** [ahochsteger/gmail2gdrive#14] opened 2017-06-02 09:20 UTC
How not to save duplicate files? I.e. signature pictures and all that

**Comment by ymcata** [comment] 2018-03-20 13:21
Hi, this script works like a charm. How to overwrite existing files?

**Comment by ahochsteger** [comment] 2019-04-28 12:29
May you have a look at https://github.com/ahochsteger/gmail2gdrive/issues/19 if that solves your problem?
Closing as duplicate of #19.

**Closed by ahochsteger** 2019-04-28 12:29 UTC
